region: us
version: '2'
authtoken: 30ddlxh90FY8xIpX8pxpfdi2dxe_5QR26moDvPBskJjJs52u9
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http