region: us
version: '2'
authtoken: 2V6OQHziguXM6b20yoU6Gx9buDa_7gUjyoDZVjLHeywG1gmTp
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http
